"""Added  is_active for Post, Comment

Revision ID: 8dd214f55a4d
Revises: 38a65bdee34d
Create Date: 2024-10-20 18:50:31.776832

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8dd214f55a4d"
down_revision: Union[str, None] = "38a65bdee34d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comment", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("post", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "is_active")
    op.drop_column("comment", "is_active")
    # ### end Alembic commands ###
